# Generated by Django 4.0 on 2021-12-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user_type', models.CharField(blank=True, choices=[('USER_REGULAR', 'REGULAR'), ('USER_ADMIN', 'ADMIN')], max_length=20)),
            ],
        ),
    ]
